# Generated by Django 4.1.3 on 2022-11-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_p', models.CharField(max_length=25)),
                ('apellido_m', models.CharField(max_length=25)),
            ],
        ),
    ]
