# Generated by Django 4.1.3 on 2022-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0003_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesionalAtendio', models.CharField(max_length=25)),
                ('anamnesisAnterior', models.CharField(max_length=250)),
                ('medicamentosRecetados', models.CharField(max_length=250)),
                ('examenesSolicitados', models.CharField(max_length=250)),
                ('alergias', models.CharField(max_length=125)),
                ('historialEnfermedades', models.CharField(max_length=500)),
                ('medicamentosQueToma', models.CharField(max_length=250)),
                ('diagnosticoObtenido', models.CharField(max_length=500)),
                ('observaciones', models.CharField(max_length=250)),
            ],
        ),
    ]
